// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZNUXPSYPEBozAAlqRfTBg8Rxt5TV2sbE',
    appId: '1:1057870139449:web:46a942f77c0813903ffde8',
    messagingSenderId: '1057870139449',
    projectId: 'authentication-2226f',
    authDomain: 'authentication-2226f.firebaseapp.com',
    storageBucket: 'authentication-2226f.appspot.com',
    measurementId: 'G-SHHPMB5VPP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5zYNCjkQc651qfIfoIyAsVj9PiBMn9bE',
    appId: '1:1057870139449:android:34773a7aa82c7d1b3ffde8',
    messagingSenderId: '1057870139449',
    projectId: 'authentication-2226f',
    storageBucket: 'authentication-2226f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvTk3edm-aDa-MqR8xKD--MZyaXX8Z4Us',
    appId: '1:1057870139449:ios:278b52aa86d32a423ffde8',
    messagingSenderId: '1057870139449',
    projectId: 'authentication-2226f',
    storageBucket: 'authentication-2226f.appspot.com',
    iosClientId: '1057870139449-qh17b4lg2eeaov76gpkkrbpf9gb98h5q.apps.googleusercontent.com',
    iosBundleId: 'com.example.login',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvTk3edm-aDa-MqR8xKD--MZyaXX8Z4Us',
    appId: '1:1057870139449:ios:278b52aa86d32a423ffde8',
    messagingSenderId: '1057870139449',
    projectId: 'authentication-2226f',
    storageBucket: 'authentication-2226f.appspot.com',
    iosClientId: '1057870139449-qh17b4lg2eeaov76gpkkrbpf9gb98h5q.apps.googleusercontent.com',
    iosBundleId: 'com.example.login',
  );
}
